<html>
<head>
  <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <meta name="author"      content="Ignasi Ortiz, Carlos Leichner, Gabriel Farrus" />
	<meta name="description" content="IT Academy - FullStack LAMP" />
    <title>PhP Developers</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    
    <nav class="flex justify-center space-x-4">
        
        
        <a href="/return/index/" class="font-bold px-3 py-2 text-slate-700 rounded-lg hover:bg-slate-100 hover:text-slate-900">Index</a>
        
      </nav>
    
    
      <form method = "POST" class="flex justify-center p-10">
        <label class="block">
          <span class=" block text-sm font-medium text-slate-700">Username:</span>
          <!-- Using form state modifers, the classes can be identical for every input -->
          <input type="text" value="" name ="inpName" class="mt-1  px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400
            focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500
            disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none
            invalid:border-pink-500 invalid:text-pink-600
            focus:invalid:border-pink-500 focus:invalid:ring-pink-500
          "/>
          <span class=" block text-sm font-medium text-slate-700">Rol:</span>
          <!-- Using form state modifers, the classes can be identical for every input -->
          <input type="text" value="" name="inpRol" class="mt-1  px-3 py-2 bg-white border border-slate-300 rounded-md text-sm shadow-sm placeholder-slate-400
            focus:outline-none focus:border-sky-500 focus:ring-1 focus:ring-sky-500
            disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none
            invalid:border-pink-500 invalid:text-pink-600
            focus:invalid:border-pink-500 focus:invalid:ring-pink-500
          "/>


        </label>
        <!-- ... -->
        <button type="submit"  class=" bg-sky-500 px-3 hover:bg-green-700 ">
          <a href="/return/index/">Continue</a>
         </button>

        <button type="submit" class=" bg-sky-500 px-3 hover:bg-red-700 ...">
          <a href="/return/index/">Cancel</a>
        </button>
        
      </form>
      
    <madre method = "POST"  class="flex justify-center space-x-4 ">

         <button type="submit"  class=" bg-sky-500 px-3 hover:bg-green-700 ">
          <a href="/return/index/">Continue</a>
         </button>

        <button type="submit" class=" bg-sky-500 px-3 hover:bg-red-700 ...">
          <a href="/return/index/">Cancel</a>
        </button>

    </madre>
      
      <padre method = "POST"  class="flex flex-center m-4">

         <a href="/users/add/" class=" flex-wrap bg-clip-border p-6 border-8 border-black group block max-w-xs mx-auto rounded-lg p-6 bg-white ring-1 ring-slate-900/5 shadow-lg space-y-3 hover:bg-sky-500 hover:ring-sky-500">
            <div class="flex items-center space-x-3">
            <svg class=" h-6 w-6 stroke-sky-500 group-hover:stroke-white" fill="none" viewBox="0 0 24 24"><!-- ... --></svg>
            <h3 class=" text-slate-900 group-hover:text-white text-sm font-semibold">Create user.</h3>
            </div>
            <p class="text-slate-500 group-hover:text-white text-sm">Create a new user from a work a task.</p>
        </a>

      
        

      </padre>

      <hijo method = "POST"  class="flex flex-center m-4">

        <a href="/task/create/" class=" bg-clip-border p-6 border-8 border-red-800 group block max-w-xs mx-auto rounded-lg p-6 bg-white ring-1 ring-slate-900/5 shadow-lg space-y-3 hover:bg-sky-500 hover:ring-sky-500">
          <div class="flex items-center space-x-3">
          <svg class=" h-6 w-6 stroke-sky-500 group-hover:stroke-white" fill="none" viewBox="0 0 24 24"><!-- ... --></svg>
          <h3 class="text-slate-900 group-hover:text-white text-sm font-semibold">Create task.</h3>
          </div>
          <p class="text-slate-500 group-hover:text-white text-sm">Create a task from a work a user.</p>
        </a>

       <a href="/task/view/" class=" bg-clip-border p-6 border-8 border-red-800 group block max-w-xs mx-auto rounded-lg p-6 bg-white ring-1 ring-slate-900/5 shadow-lg space-y-3 hover:bg-sky-500 hover:ring-sky-500">
          <div class="flex items-center space-x-3">
          <svg class=" h-6 w-6 stroke-sky-500 group-hover:stroke-white" fill="none" viewBox="0 0 24 24"><!-- ... --></svg>
          <h3 class="text-slate-900 group-hover:text-white text-sm font-semibold">View task.</h3>
          </div>
          <p class="text-slate-500 group-hover:text-white text-sm">View a task from a work a user.</p>
        </a>

    

        <a href="/task/update/" class=" bg-clip-border p-6 border-8 border-red-800 group block max-w-xs mx-auto rounded-lg p-6 bg-white ring-1 ring-slate-900/5 shadow-lg space-y-3 hover:bg-sky-500 hover:ring-sky-500">
          <div class="flex items-center space-x-3">
          <svg class=" h-6 w-6 stroke-sky-500 group-hover:stroke-white" fill="none" viewBox="0 0 24 24"><!-- ... --></svg>
          <h3 class="text-slate-900 group-hover:text-white text-sm font-semibold">Modify task.</h3>
          </div>
          <p class="text-slate-500 group-hover:text-white text-sm">Modify a new task from a work a user.</p>
        </a>



        <a href="/task/delete/" class=" bg-clip-border p-6 border-8 border-red-800 group block max-w-xs mx-auto rounded-lg p-6 bg-white ring-1 ring-slate-900/5 shadow-lg space-y-3 hover:bg-sky-500 hover:ring-sky-500">
          <div class="flex items-center space-x-3">
          <svg class=" h-6 w-6 stroke-sky-500 group-hover:stroke-white" fill="none" viewBox="0 0 24 24"><!-- ... --></svg>
          <h3 class="text-slate-900 group-hover:text-white text-sm font-semibold">Delete task.</h3>
          </div>
          <p class="text-slate-500 group-hover:text-white text-sm">Delete a new task from a work a user.</p>
        </a>

  </hijo>

    
    <footer class="mt-1  px-3 py-2">
      <p class="font-extrabold text-2xl bg-blue-400 text-center"><b>IT Academy (itinerari LAMP) - Cibernàrium de BcnActiva - 2022</b></p>
    </footer>

</body>
</html>