<?php 
    session_start();
    if (isset($_SESSION['user_id'])) {
        // header('Location: index');
        header('Location: listtask');
    }
    // include ROOT_PATH.'/web/includes/header.php';
?>

<!-- <head>
  <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <meta name="author"      content="Ignasi Ortiz, Carlos Leichner, Gabriel Farrus" />
	<meta name="description" content="IT Academy - FullStack LAMP" />
    <title>PhP Developers</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head> -->

    <form id="frmLogin" action="index" method="post">
        <section class="flex justify-center items-center h-4/5 bg-gray-300">
            <div class="max-w-md w-full bg-white rounded p-6 my-44 space-y-4">
                <div class="mb-4">
                    <p class="text-gray-600">Benvingut a la:</p>
                    <h2 class="text-xl text-pink-600 font-bold">IT-ACADEMY Developers Team v2.0</h2>
                </div>
                <div>
                    <input type ="text" 
                            id   ="inpName"
                            name ="inpName" 
                            placeholder="Name"
                            class="w-full p-4 text-sm bg-gray-50 focus:outline-none focus:bg-yellow-100 border-2 border-gray-400 rounded text-gray-600">
                </div>
                <div>
                    <input type ="password" 
                            id   ="inpPwd"
                            name ="inpPwd"
                            placeholder="Password"
                            class="w-full p-4 text-sm bg-gray-50 focus:outline-none focus:bg-yellow-100 border-2 border-gray-400 rounded text-gray-600">
                </div>
                <div>
                    <button type ="submit"  
                            id   ="btnLogin" 
                            name ="btnLogin"
                            value="Accedeix"
                            form ="frmLogin" 
                            class="w-full py-4 bg-pink-600 hover:bg-pink-800 rounded text-sm font-bold text-gray-50 transition duration-200">Accedeix
                    </button>
                </div>

                <div class="flex flex-col justify-start">
                    <div class="flex flex-row">
                        <input type="checkbox" 
                               name="remember"
                               class="checkbox focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300 rounded">
                        <span  id="chkSlider" 
                               class="slider round">
                        </span>        
                        <label for="remember" 
                               class="mx-2 text-sm font-normal text-gray-600">Recorda'm
                        </label>
                        <select id="rememberTime" name="rememberTime">
                            <option value="3600" selected>1 hora</option>
                            <option value="86400">24 hores</option>
                            <option value="604800">1 setmana</option>
                            <option value="2592000">1 mes</option>
                        </select>
                    </div>
                    <div class="flex justify-center">
                        <?php 
                            if (isset($_POST['inpName'])){
                                echo '<span class="mt-4"> <a class="text-lg font-bold justify-end text-red-600 hover:underline" href="adduser">Usuari no trobat. Vols registrar-te?</a></span>';
                            }
                        ?>                    
                    </div>
                </div>
            </div>
        </section>
    </form>      
